// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    PreloaderAnimation: typeof import('./components/PreloaderAnimation.vue')['default']
    README: typeof import('./components/README.md')['default']
    ScrollToTopBtn: typeof import('./components/ScrollToTopBtn.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    ToastNotfication: typeof import('./components/ToastNotfication.vue')['default']
  }
}

export { }
